---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать профиль
  - Пользователь должен иметь возможность выбрать язык программирования для решения задач (Clojure, Cpp, Csharp, Dart, Elixir, Go, Haskell, Java, Javascript, Kotlin, Php, Python, Ruby, Rust, Typescript) 
  - Пользователь должен иметь возможность создать новую игру
  - При создании новой игры пользователь должен иметь возможность выбрать её сложность
  - При создании новой игры пользователь должен иметь возможность указать продолжительность игры 
  - При создании новой игры пользователь должен иметь возможность выбрать направление задачи, которая будет решаться 
  - При создании новой игры пользователь должен иметь возможность выбора игры со случайным человеком
  - При создании новой игры пользователь должен иметь возможность выбора игры с другом
  - При создании новой игры пользователь должен иметь возможность выбора игры с ботом
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность писать в чат
  - Пользователь должен иметь возможность посмотреть законченную игру в записи
  - Пользователь должен иметь возможность получать очки за игры
  - Пользователь должен иметь возможность двигаться в рейтинге 
