---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать профиль
  - Пользователь должен иметь возможность выбрать язык программирования, соответствуя которому будут отображаться задачи
  - Пользователь должен иметь возможность создать новую игру
  - При создании новой игры пользователь должен иметь возможность выбрать её сложность
  - При создании новой игры пользователь должен иметь возможность указать продолжительность игры 
  - При создании новой игры пользователь должен иметь возможность выбрать направление задачи, которая будет решаться 
  - При создании новой игры пользователь должен иметь возможность выбора игры со случайным человеком
  - При создании новой игры пользователь должен иметь возможность выбора игры с другом
  - При создании новой игры пользователь должен иметь возможность выбора игры с ботом
